Feature: Footer
LTD-Via-corpvs/dripstore-estacio pull request #9
Opened 2024-04-03 19:25 UTC by Mateusinbessa

2024-04-05 14:07 UTC, jpedro002 requested changes
corrige la

2024-04-05 14:07 UTC, jpedro002 commented on public/group.svg
se deletar esse vai tirar ele do meu header 
![Captura de tela 2024-04-05 101331](https://github.com/LTD-Via-corpvs/dripstore-estacio/assets/122836400/bab0fe7b-b04f-4a9e-aa64-34a8d1fe7d63)

2024-04-05 17:11 UTC, jpedro002 reviewed
ta massa 
![61802cf3bffa8ff88fb5127446e318ad](https://github.com/LTD-Via-corpvs/dripstore-estacio/assets/122836400/f3f2af35-ad2c-40ad-ad2c-0de99ccfe781)

2024-04-05 17:11 UTC, jpedro002 approved these changes

2024-04-09 20:28 UTC, KingTimer12 approved these changes

2024-04-10 12:41 UTC, merged